### ISSUE TITLE
This is out of date with the main factoryGuy repo

### ISSUE THREAD

**Issue by Andrew-Max** [cristinawithout/ember-cli-data-factory-guy#11]
The installer here downloads an older version of factory guy which has conflicts with the current factory guy documentation. 

I now see that it does see that at the top of the repo but it is still not very clear. It would be very helpful if the readme made it more explicit that this repo is essentially defunct

**Comment by danielspaniel** [comment]
Will do that ASAP .. thanks for reminder .. will put notice on my repo to not use that other older one
