### ISSUE TITLE
Warning generated when used with v0.2.0 of ember-cli

### ISSUE THREAD

**Issue by ezpuzz** [cristinawithout/ember-cli-data-factory-guy#7]
```
The package `ember-cli-data-factory-guy` is not a properly formatted package, we have used a fallback lookup to resolve it at `/home/vagrant/sage-ui/node_modules/ember-cli-data-factory-guy`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
```

They recently changed the requirements for addons, so I assume it is due to that.

**Comment by danielspaniel** [comment]
Taking a look at this in the next few days.

**Comment by cristinawithout** [comment]
Should be fixed on https://github.com/cristinawithout/ember-cli-data-factory-guy/pull/8

**Comment by ezpuzz** [comment]
it's fixed, you could bump the version :wink:

**Comment by cristinawithout** [comment]
Oops. I did create the new tag but forgot to also update package.json. I recreated the v0.9.2 tag with updated package.json.
